/* Compares the average customer satisfaction score generated by the lowest-performing seller decile against the overall platform average to measure brand damage. */
WITH delay_cte AS(
    SELECT order_items.seller_id,
     ROUND(AVG(EXTRACT(EPOCH FROM o.order_delivered_customer_date) - EXTRACT(EPOCH FROM o.order_purchase_timestamp)) / 86400, 2) AS avg_delivery_time,
     ROUND(AVG(CASE 
            WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1.0
            ELSE 0.0 
        END) * 100, 2) AS pct_late

FROM orders o
JOIN order_items ON order_items.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY order_items.seller_id
HAVING COUNT(o.order_id) > 10
), ntile_cte AS (
        SELECT * , NTILE(10) OVER(ORDER BY pct_late DESC) AS decile
FROM delay_cte
)

SELECT ROUND(AVG(order_reviews.review_score), 2) AS worst_sellers_avg_review,
    (SELECT ROUND(AVG(review_score), 2) FROM order_reviews) AS platform_avg_review

FROM ntile_cte 
JOIN order_items ON order_items.seller_id = ntile_cte.seller_id
JOIN order_reviews ON order_reviews.order_id = order_items.order_id
WHERE decile = 1


